In [2]:
import numpy as np
np.random.random()

0.7503418704000268

In [3]:
np.random.seed(80) # rastgele üretilen sayıyı sabit tutar
print("Gap")
np.random.random()

Gap


0.5219157165002548

In [4]:
np.random.random(4)

array([0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [5]:
np.random.random(10)

array([0.6851502 , 0.21165334, 0.31726607, 0.2672994 , 0.12050632,
       0.9968569 , 0.08043969, 0.28459975, 0.5352502 , 0.84580211])

In [6]:
x = np.random.random(5)
x

array([0.20012414, 0.81204355, 0.37293679, 0.80964124, 0.01199526])

In [7]:
y = np.append(x,np.random.random(5))
y

array([0.20012414, 0.81204355, 0.37293679, 0.80964124, 0.01199526,
       0.66806941, 0.2905242 , 0.32271981, 0.41770991, 0.486396  ])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.ones((4,4),dtype=np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [12]:
np.empty(5)

array([0.66806941, 0.2905242 , 0.32271981, 0.41770991, 0.486396  ])

In [13]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [14]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
np.arange(5,50,5).reshape(3,3)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

* (np.linspace): belirtilen bir aralıkta eşit aralıklarla dağılmış sayılardan oluşan bir dizi oluşturmak için kullanılan NumPy kütüphanesinin bir fonksiyonudur.

In [16]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
np.linspace(1,10,6).reshape(2,3)

array([[ 1. ,  2.8,  4.6],
       [ 6.4,  8.2, 10. ]])

In [18]:
np.linspace(1,10,6,endpoint=False)

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [19]:
x = 9 
np.sqrt(x)

np.float64(3.0)

In [20]:
np.power(3,4)

np.int64(81)

In [21]:
np.array([1,2,3,4,5]) #1D array

array([1, 2, 3, 4, 5])

In [22]:
np.array([[2,3],[4,5],[7,8]]) #2D array

array([[2, 3],
       [4, 5],
       [7, 8]])

In [23]:
a = np.array([[[3,4,5],[1,2,3],[7,8,9]]])
print(a)
print(a.ndim)
print(a.shape)

[[[3 4 5]
  [1 2 3]
  [7 8 9]]]
3
(1, 3, 3)


In [24]:
np.identity(5) # nxn boyutlu birim matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(20,29).reshape(3,3)
np.dot(x,y)

array([[144, 150, 156],
       [351, 366, 381],
       [558, 582, 606]])

In [27]:
x = np.arange(1,20)
x[6:]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
x[:6]

array([1, 2, 3, 4, 5, 6])

In [29]:
y = np.arange(1,10).reshape(3,3)
y[:,2]

array([3, 6, 9])

In [30]:
y[1,2]

np.int64(6)

In [31]:
y%2==0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [32]:
y[y>5]

array([6, 7, 8, 9])

In [33]:
np.std(y)

np.float64(2.581988897471611)

In [34]:
np.std(y,axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [35]:
np.mean(y)

np.float64(5.0)

In [36]:
np.median(y)

np.float64(5.0)

In [37]:
np.sum(y)

np.int64(45)

In [39]:
np.sum(y,axis=1)

array([ 6, 15, 24])

In [40]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
x = np.random.randint(1,50,20)
np.random.choice(x,10,replace=True)

array([ 2, 27, 28, 27, 27,  9, 25, 27, 47,  9])

In [42]:
x

array([47, 10, 25, 39, 25,  2, 45, 18, 39, 17, 42, 21, 32, 25,  4,  9, 28,
       47,  4, 27])

In [43]:
np.random.choice(x,6,replace=True).reshape(2,3)

array([[39, 28,  4],
       [28, 47, 45]])

In [47]:
x = np.random.random(10)
x

array([0.57529683, 0.91596778, 0.91577347, 0.00538354, 0.59148681,
       0.01569104, 0.21055363, 0.72428231, 0.14370082, 0.69737182])

In [48]:
np.unique(x,3)

(array([0.00538354, 0.01569104, 0.14370082, 0.21055363, 0.57529683,
        0.59148681, 0.69737182, 0.72428231, 0.91577347, 0.91596778]),
 array([3, 5, 8, 6, 0, 4, 9, 7, 2, 1]))